name: CI

on:
  push:
    branches: [ "master" ]

jobs:
  MiniCC-Test:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        compiler: [gcc, clang]

    steps:
    - uses: actions/checkout@v3
    - name: install toolchain and runtime
      run: |
        sudo apt-get -y update
        sudo apt-get -y install ${{ matrix.compiler }} make gcc-riscv64-linux-gnu qemu-user-static
    - name: build minicc
      env:
        CC: ${{ matrix.compiler }}
      run: make
    - name: run test
      run: make test
